server:
  port: 20001

spring:
  application:
    name: res-gateway
  cloud:
    nacos:
      discovery:
        namespace: online-retailers
        server-addr: localhost:8848
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**

        - id: user
          uri: lb://user
          predicates:
            - Path=/auth/**

        - id: fileUpload
          uri: lb://fileUpload
          predicates:
            - Path=/upload/**

        - id: idGenerator
          uri: lb://idGenerate
          predicates:
            - Path=/idGenerator/**
            - TimeLimitBetween=06:00,22:00
          filters:
            - StripPrefix=1

        - id: test
          uri: lb://test-consumer-service
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1


      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# 监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  simple:
    metrics:
      export:
        enabled: true

token:
  secret: a-string-secret-at-least-256-bits-long

rights:
  exclude-paths:  #自定义的属性，用于排除直接访问某些路径
    - /admin/**
    - /cust/**
    - /back/**
