spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        namespace: online-retailers
        server-addr: localhost:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_retailers?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 2333
server:
  port: 8381
