server:
  port: 11000

spring:
  application:
    name: fileUpload  #服务名称
  cloud:
    nacos:
      discovery:
        namespace: online-retailers
        server-addr: localhost:8848
        username: nacos
        password: nacos
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  data:
    redis:
      host: localhost
      port: 6379
      database: 1 # 选择数据库

aliyun:
  oss:
    endpoint: ${oss.endpoint:oss-cn-beijing.aliyuncs.com}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: ${oss.bucketName:go-where}
    urlPrefix: ${oss.urlPrefix:http://go-where.oss-cn-beijing.aliyuncs.com}


#监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  simple:
    metrics:
      export:
        enabled: true

# 上线时，要关闭swagger       上线时利用命令行参数或虚拟机参数关闭
springdoc:
  swagger-ui:
    enabled: true   # 禁用 swagger UI
